Repository EAT-SSU/iOS, pull requests merged in 2024-12, with the labels that each got.

#191 [#190] splashChristmas 파일 위치 변경
  EATSSU_MVC/EATSSU_MVC/Resources/splashChristmas.png
Labels: 📲 Feat

#193 [#192] 크리스마스ver 스플래시 이미지 짤림 현상 수정
  EATSSU_MVC/EATSSU_MVC/Resources/Assets/Images.xcassets/version2/SplashChristmas.imageset/SplashChristmas.png
  EATSSU_MVC/EATSSU_MVC/Resources/Assets/Images.xcassets/version2/splashChistmasBackground.imageset/Contents.json
  EATSSU_MVC/EATSSU_MVC/Resources/Assets/Images.xcassets/version2/splashChistmasBackground.imageset/splashChistmasBackground.png
  EATSSU_MVC/EATSSU_MVC/Resources/Assets/Images.xcassets/version2/splashChristmasLogo.imageset/Contents.json
  EATSSU_MVC/EATSSU_MVC/Resources/Assets/Images.xcassets/version2/splashChristmasLogo.imageset/Logo_iOS.png
  EATSSU_MVC/EATSSU_MVC/Resources/LaunchScreen.storyboard
  EATSSU_MVC/EATSSU_MVC/Resources/splashChristmas.png
Labels: 🛠️ Fix

#196 [#195] ReviewV2 폴더구조 세팅
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/ReviewV2/View/V2ReviewView.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/ReviewV2/ViewController/V2ReviewViewController.swift
Labels: 📲 Feat

#200 [#199] 고정/변동메뉴 조회 DTO 변경사항 prod 적용
  EATSSU_MVC/EATSSU_MVC/Sources/Data/Network/DTO/Home/ChangeMenuTableResponse.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Data/Network/DTO/Home/FixedMenuTableResponse.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/Home/Enum/MenuTypeInfo.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/Home/View/RestaurantTableView/RestaurantTableViewMenuCell.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/Home/ViewController/HomeRestaurantViewController.swift
Labels: 🛠️ Fix

#204 [#203] Tuist 사용 버전 명시
  .github/README.md
Labels: ⚙️ Setting

#205 [#201] 불필요한 파일 제거 및 더 이상 사용하지 않는 사항 변경
  EATSSUDesign/Tuist/Tuist.swift
  EATSSU_MVC/EATSSU_MVC/Resources/Preview Content/Preview Assets.xcassets/Contents.json
  EATSSU_MVC/Tuist/Tuist.swift
  EATSSU_MVVM/Tuist/Tuist.swift
  Tuist/Tuist.swift
Labels: ⚙️ Setting

#212 [add] git-hooks 설치 파일 추가
  install-hooks.sh
Labels: 📲 Feat
