Repository EAT-SSU/iOS, pull requests merged in 2024-11, with the labels that each got.

#148 [#147] tuist = latest로 변경
  .mise.toml
Labels: 📝 Setting

#152 [#149] "둘러보기" 버튼 힘 빼기
  EATSSUDesign/EATSSUDesign/Sources/DesignSystem/Button/ESButton.swift
  EATSSUDesign/EATSSUDesign/Sources/DesignSystem/ReportButton/ESReportButton.swift
  EATSSUDesign/EATSSUDesign/Sources/DesignSystem/TextField/ESTextField.swift
  EATSSU_MVC/EATSSU_MVC/Resources/Assets/Images.xcassets/version2/LookAroundButton.imageset/LookAroundButton.svg
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/Auth/View/LoginView.swift
Labels: 🪄 Refactor

#155 [#154] SnapKit & Kingfisher Dynamic Framework로 전환
  Tuist/Package.swift
Labels: ⚙️ Setting

#156 [#61] enum 값을 통한 식당 관리 및 방학여부 확인하여 isVacation 적용
  EATSSU_MVC/EATSSU_MVC/Sources/Data/Firebase/FirebaseRemoteConfig.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/Auth/ViewController/LoginViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/Home/Enum/RestaurantType.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/Home/ViewController/HomeRestaurantViewController.swift
Labels: 📲 Feat, 🪄 Refactor

#160 [#153] MyPageViewController에서 비즈니스 로직 Model로 분리
  EATSSU_MVC/EATSSU_MVC/Resources/Localizable.xcstrings
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/MyPage/Model/MyPageModel.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/MyPage/ViewController/MyPageViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Literal/TextLiteral.swift
Labels: 🪄 Refactor

#177 [#174] 강제 업데이트 로직 활성화
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Application/SceneDelegate.swift
Labels: 📲 Feat

#178 [#176] 누락된 Firebase 모듈 추가
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/Auth/Model/LoginModel.swift
Labels: 🛠️ Fix

#183 [#182] iOS 최소 지원 버전 15->16 변경
  EATSSU_MVC/Project.swift
Labels: ⚙️ Setting

#184 [#90] `16+`의 모달 Sheet UI 작업 완료
  EATSSU_MVC/EATSSU_MVC/Sources/Data/Network/DTO/Review/TotalReviewResponse.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Data/Network/Router/ReviewRouter.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/Auth/View/LoginView.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/Home/View/RestaurantTableView/RestaurantTableViewHeader.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/Home/ViewController/HomeViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/Review/ViewController/LoginPromptViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Literal/TextLiteral.swift
Labels: 📲 Feat
