Repository EAT-SSU/iOS, pull requests merged in 2024-09, with the labels that each got.

#5 [#4] 배포용 앱 이름 변경 및 API 키 호출 문제 해결
  EATSSU_MVC/Project.swift
  EATSSU_MVVM/Project.swift
Labels: 🛠️ Fix

#11 [#9] MVVM 프로젝트 비활성화
  Workspace.swift
Labels: 📲 Feat

#8 [#7] "만든사람들" 페이지 설계
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/version2/Creators.imageset/Contents.json
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/version2/Creators.imageset/Creators.png
  EATSSU_MVC/EATSSU_MVC/Sources/Notification/NotificationManager.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Screen/MyPage/Model/MyPageModel.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Screen/MyPage/View/CreatorsView.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Screen/MyPage/ViewController/CreatorViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Screen/MyPage/ViewController/MyPageViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Application/AppDelegate.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Application/AppStoreCheck.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Application/SceneDelegate.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Base/BaseUIView.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Literal/TextLiteral.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Namespace/MyPageLabels.swift
Labels: 📲 Feat

#13 [#6] 2.0.0 앱 아이콘 변경
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/100.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/1024 1.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/1024.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/114.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/120.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/128.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/144.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/152.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/16.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/167.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/172.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/180.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/196.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/20.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/216.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/256.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/29.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/32.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/40.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/48.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/50.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/512.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/55.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/57.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/58.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/60.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/64.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/66.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/72.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/76.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/80.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/87.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/88.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/92.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/AppIcon.appiconset/Contents.json
Labels: 📲 Feat

#15 [#14] 최소 배포 OS 버전 수정
  EATSSU_MVC/Project.swift
Labels: 📝 Setting

#20 [#16] 리뷰 페이지 다중 메뉴 선택 [라디오버튼 -> 체크버튼] 변경
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/version2/ic_check.imageset/Contents.json
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/version2/ic_check.imageset/ic_check[24].png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/version2/ic_check.imageset/ic_check[24]@2x.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/version2/ic_check.imageset/ic_check[24]@3x.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/version2/ic_uncheck.imageset/Contents.json
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/version2/ic_uncheck.imageset/ic_uncheck[24].png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/version2/ic_uncheck.imageset/ic_uncheck[24]@2x.png
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/version2/ic_uncheck.imageset/ic_uncheck[24]@3x.png
  EATSSU_MVC/EATSSU_MVC/Sources/Screen/Review/View/ChoiceMenuView/ChoiceMenuTableViewCell.swift
Labels: 🛠️ Fix

#23 [#22] v2.0.1에서 개발 중인 시간 기반 알림 제거
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Application/AppDelegate.swift
Labels: 🛠️ Fix

#26 [#25] 지원하지 않는 문자형식으로 인해 배포되지 않는 문제 해결
  EATSSU_MVC/Project.swift
Labels: 🛠️ Fix

#31 [#29 & #30] 마이페이지에서 셀을 선택했을 때 발생하는 문제를 해결
  EATSSU_MVC/EATSSU_MVC/Sources/Screen/MyPage/ViewController/MyPageViewController.swift
Labels: 🛠️ Fix

#34 [#33] Kakao iOS SDK 버전 2.22.5로 전환
  Tuist/Package.swift
Labels: 🛠️ Fix

#35 [qa] 카카오앱 로그인 불가 현상을 위한 긴급조치
  Tuist/Package.swift
Labels: 🛠️ Fix

#40 [#36] 카카오톡 앱으로 로그인이 되지 않는 문제 해결
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Application/AppDelegate.swift
  EATSSU_MVC/Project.swift
Labels: 🛠️ Fix

#44 [#43] 홈에서 사용 중인 잘못된 메인 로고 이미지 교체
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/version2/MainLogoSmall.imageset/Contents.json
  EATSSU_MVC/EATSSU_MVC/Resources/Images.xcassets/version2/MainLogoSmall.imageset/MainLogoSmall.svg
  EATSSU_MVC/EATSSU_MVC/Sources/Screen/Home/ViewController/HomeViewController.swift
Labels: 🛠️ Fix

#51 [#50] CI 파이프라인 구축
  .github/workflows/upload_product.yml
Labels: 📲 Feat

#60 [#55] 스낵코너 메뉴 활성화 및 푸드코트 테이블 제거
  EATSSU_MVC/EATSSU_MVC/Sources/Screen/Home/Enum/RestaurantLocation.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Screen/Home/ViewController/HomeRestaurantViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Literal/TextLiteral.swift
Labels: 🛠️ Fix

#62 [#48] Fastlane 도입
  .github/workflows/cicd-automation.yml
  .github/workflows/continuous-integration.yml
  .gitignore
  EATSSU_MVC/EATSSU_MVC/UITests/SampleTests.swift
  EATSSU_MVC/EATSSU_MVC/UITests/SnapshotHelper.swift
  EATSSU_MVC/EATSSU_MVC/UnitTests/SampleTests.swift
  EATSSU_MVC/Project.swift
  Gemfile
  Gemfile.lock
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/README.md
  fastlane/Snapfile
  fastlane/SnapshotHelper.swift
  fastlane/report.xml
Labels: 📲 Feat

#63 [#1] 시간 기반 알림 발송 기능 설계
  EATSSU_MVC/EATSSU_MVC/Sources/Notification/NotificationManager.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Application/AppDelegate.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Literal/TextLiteral.swift
Labels: 📲 Feat

#64 [v2.1.0.1] TestFlight 업로드
  .github/workflows/cicd-automation.yml
  .github/workflows/continuous-integration.yml
  .gitignore
  EATSSU_MVC/EATSSU_MVC/Sources/Notification/NotificationManager.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Screen/Home/Enum/RestaurantLocation.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Screen/Home/ViewController/HomeRestaurantViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Application/AppDelegate.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Literal/TextLiteral.swift
  EATSSU_MVC/EATSSU_MVC/UITests/SampleTests.swift
  EATSSU_MVC/EATSSU_MVC/UITests/SnapshotHelper.swift
  EATSSU_MVC/EATSSU_MVC/UnitTests/SampleTests.swift
  EATSSU_MVC/Project.swift
  Gemfile
  Gemfile.lock
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/README.md
  fastlane/Snapfile
  fastlane/SnapshotHelper.swift
  fastlane/report.xml
Labels: 🧪 QA Test

#75 [#52] "문의하기" 외부 링크가 아닌, 카카오톡 앱으로 연결되도록 변경
  EATSSU_MVC/EATSSU_MVC/Sources/Screen/MyPage/ViewController/MyPageViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Namespace/MyPageLabels.swift
  EATSSU_MVC/Project.swift
Labels: 🛠️ Fix

#76 [v2.1.0.2] "문의하기" 탭했을 때 카카오톡앱의 채팅방으로 연결되는 것을 확인합니다.
  .github/ISSUE_TEMPLATE/bug-report.md
  EATSSU_MVC/EATSSU_MVC/Sources/Screen/MyPage/ViewController/MyPageViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Namespace/MyPageLabels.swift
  EATSSU_MVC/Project.swift
Labels: 🧪 QA Test

#79 [#77] TalkApi를 사용해도 "문의하기" 탭에서 카카오톡앱으로 연결되지 않는 문제 해결
  EATSSU_MVC/EATSSU_MVC/Sources/Screen/MyPage/ViewController/MyPageViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Literal/TextLiteral.swift
  EATSSU_MVC/Project.swift
Labels: 🛠️ Fix

#80 [v2.1.0.3] Info.plist에 누락된 kakaoplus 값을 넣고 테스트
  EATSSU_MVC/EATSSU_MVC/Sources/Screen/MyPage/ViewController/MyPageViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Literal/TextLiteral.swift
  EATSSU_MVC/Project.swift
Labels: 🧪 QA Test

#82 [#66] 가격라벨 정렬 기준 수정
  EATSSU_MVC/EATSSU_MVC/Sources/Screen/Home/View/RestaurantTableView/RestaurantTableViewMenuCell.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Extension/Int+.swift
Labels: 🛠️ Fix

#84 [#83] BaseView & BaseViewController 코드 내 문서 작성 및 추상화 강화
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Base/BaseUIView.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Base/BaseViewController.swift
Labels: 🪄 Refactor

#87 [#28] 마이페이지 사용자 정보 데이터 바인딩 시, realm 사용
  EATSSU_MVC/EATSSU_MVC/Sources/Network/LocalDB/NickName.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Network/LocalDB/RealmService.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Network/LocalDB/UserInfo.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Network/LocalDB/UserInfoManager.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Screen/Auth/ViewController/LoginViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Screen/Auth/ViewController/SetNickNameViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Screen/MyPage/View/MyPageView.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Screen/MyPage/ViewController/MyPageViewController.swift
  Tuist/Package.resolved
  Tuist/Package.swift
Labels: 🛠️ Fix

#92 [#91] ImageLiteral에서 사용 중인 이미지 파일 경로 재참조
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Literal/ImageLiteral.swift
Labels: 🛠️ Fix

#93 [#78] 토글 스위치 앱 저장소 보관 & 리디자인된 마이페이지 UI 구축 및 비즈니스 로직 연결
  EATSSU_MVC/EATSSU_MVC/Resources/Assets/Images.xcassets/version2/WithdrawIcon.imageset/Contents.json
  EATSSU_MVC/EATSSU_MVC/Resources/Assets/Images.xcassets/version2/WithdrawIcon.imageset/Unsubscribe.png
  EATSSU_MVC/EATSSU_MVC/Sources/Notification/NotificationManager.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/MyPage/Enum/MyPageLabels.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/MyPage/Model/MyPageLocalData.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/MyPage/Model/MyPageModel.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/MyPage/Model/MyPageRightItemData.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/MyPage/View/Cell/MyPageServiceCell.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/MyPage/View/MyPageView.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/MyPage/View/MyPageView/Cell/MyPageTableDefaultCell.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/MyPage/View/MyPageView/Cell/NotificationSettingTableViewCell.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/MyPage/View/MyPageView/MyPageView.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/MyPage/View/RequestView.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/MyPage/View/UserWithdrawView.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/MyPage/ViewController/MyPageViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/MyPage/ViewController/MyReviewViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/MyPage/ViewController/ProvisionViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/MyPage/ViewController/RequestViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/MyPage/ViewController/UserWithdrawViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Base/BaseViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Literal/TextLiteral.swift
Labels: 📲 Feat

#95 [#94] 푸시 알림 수신 동의를 했을 시 토스트 메시지로 피드백합니다.
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/MyPage/ViewController/MyPageViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Extension/UIView+.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Literal/TextLiteral.swift
Labels: 📲 Feat

#99 [#96] 앱을 처음설치했을 때, OS에서 푸시 알림 동의 시 스위치 버튼을 켜두게 설정
  EATSSU_MVC/EATSSU_MVC/Sources/Notification/NotificationManager.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/MyPage/View/MyPageView/Cell/MyPageTableDefaultCell.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/MyPage/View/MyPageView/Cell/NotificationSettingTableViewCell.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/MyPage/View/MyPageView/MyPageView.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/MyPage/ViewController/MyPageViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Application/AppDelegate.swift
Labels: 📲 Feat

#106 [#101] GitHub Action Secrets 생성 파일 위치 조정
  .github/workflows/continuous-integration.yml
Labels: 🛠️ Fix

#107 [#105] 푸시 알림을 꺼도 앱 재시작시 자동으로 푸시 알림을 켜는 문제
  EATSSU_MVC/EATSSU_MVC/Sources/Notification/NotificationManager.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/MyPage/ViewController/MyPageViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Application/AppDelegate.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Application/AppStoreCheck.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Application/SceneDelegate.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Extension/UIView+.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Literal/TextLiteral.swift
Labels: 🛠️ Fix

#110 [Release] 2.1.1을 배포합니다.
  .github/workflows/continuous-integration.yml
  EATSSU_MVC/EATSSU_MVC/Sources/Notification/NotificationManager.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/MyPage/ViewController/MyPageViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Application/AppDelegate.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Application/AppStoreCheck.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Application/SceneDelegate.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Extension/UIView+.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Literal/TextLiteral.swift
Labels: 🌍 Release

#112 [#111] 푸시 알림 사용자 스위치 저장 중 알림 해제가 서비스에 반영이 되지 않는 문제
  EATSSU_MVC/EATSSU_MVC/Sources/Notification/NotificationManager.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/MyPage/ViewController/MyPageViewController.swift
Labels: 🛠️ Fix

#113 [QA] v2.1.1.2 테스트 플라이트 업로드
  .github/workflows/continuous-integration.yml
  EATSSU_MVC/EATSSU_MVC/Sources/Notification/NotificationManager.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/MyPage/ViewController/MyPageViewController.swift
Labels: 🧪 QA Test

#114 [Release] v2.1.1(2.1.1.2) 배포
  .github/workflows/continuous-integration.yml
  EATSSU_MVC/EATSSU_MVC/Sources/Notification/NotificationManager.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/MyPage/ViewController/MyPageViewController.swift
Labels: 🌍 Release

#116 [#115]
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/Review/View/RerportView/ReportView.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/Review/ViewController/ReportViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Application/SceneDelegate.swift
Labels: 🛠️ Fix

#117 [QA] v2.1.2(2.1.1.3) 배포
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/Review/View/RerportView/ReportView.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/Review/ViewController/ReportViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Application/SceneDelegate.swift
Labels: 🧪 QA Test

#122 [#121] 앱스토어 인앱 업데이트 호출 메소드 제거
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Application/SceneDelegate.swift
Labels: 🛠️ Fix

#123 [QA] v2.1.2.2 업로드
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Application/SceneDelegate.swift
Labels: 🧪 QA Test

#124 [Release] v2.1.2를 심사에 제출합니다.
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Application/SceneDelegate.swift
Labels: 🌍 Release

#128 [#126] BaseView & BaseViewController에서 런타임에러를 발생하는 코드 제거
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Base/BaseUIView.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Base/BaseViewController.swift
Labels: 🚨 HotFix

#132 [#131] 제거하지 않은 앱 버전 검사 코드 제거
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Application/SceneDelegate.swift
Labels: 🚨 HotFix

#134 [#133] firebase remote config 캐싱타임 3600->600 수정
  EATSSU_MVC/EATSSU_MVC/Sources/Data/Firebase/FirebaseRemoteConfig.swift
Labels: 🛠️ Fix

#135 [Fix] 리뷰 작성 에러 해결
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/Review/View/RateReview/RateView.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/Review/ViewController/ChoiceMenuViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/Review/ViewController/ReviewViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/Review/ViewController/SetRateViewController.swift
Labels: 🛠️ Fix

#136 [#119] 메뉴 cell 레이아웃 수정
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/Home/Enum/MenuTypeInfo.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/Home/View/RestaurantTableView/RestaurantTableViewMenuCell.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/Home/View/RestaurantTableView/RestaurantTableViewMenuTitleCell.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Presentation/Home/ViewController/HomeRestaurantViewController.swift
  EATSSU_MVC/EATSSU_MVC/Sources/Utility/Literal/TextLiteral.swift
Labels: 🛠️ Fix
