Repository EAT-SSU/iOS, pull requests merged in 2025-03, with the labels that each got.

#248 [#213, #247] 리뷰 이미지 누락 수정 및 아이폰 설정 예외처리
  EATSSU/App/Sources/Presentation/Home/ViewController/HomeTimeTabmanController.swift
  EATSSU/App/Sources/Presentation/Review/ViewController/SetRateViewController.swift
  EATSSUDesign/EATSSUDesign/Resources/Images.xcassets/AddImageButton.imageset/AddImageButton.svg
  EATSSUDesign/EATSSUDesign/Resources/Images.xcassets/AddImageButton.imageset/Contents.json
Labels: 🛠️ Fix

#253 [#252] GoogleAdMobs 관련 코드 제거
  EATSSU/App/Sources/Presentation/Home/ViewController/HomeTimeTabmanController.swift
  EATSSU/App/Sources/Presentation/Home/ViewController/HomeViewController.swift
  EATSSU/App/Sources/Presentation/Review/ViewController/SetRateViewController.swift
  EATSSU/App/Sources/Utility/Application/AppDelegate.swift
  EATSSU/Project.swift
  Tuist/Package.resolved
  Tuist/Package.swift
Labels: ⚙️ Setting

#255 [#254] Identifier 등록을 위한 widget BundleID 변경
  EATSSU/Project.swift
Labels: ⚙️ Setting

#259 [#250] 내 리뷰 페이지 UI 수정
  EATSSU/App/Sources/Presentation/MyPage/ViewController/MyPageViewController.swift
  EATSSU/App/Sources/Presentation/MyPage/ViewController/MyReviewViewController.swift
  EATSSU/App/Sources/Presentation/Review/View/SeeReview/RateNumberView.swift
  EATSSU/App/Sources/Presentation/Review/View/SeeReview/ReviewTableCell.swift
Labels: 🛠️ Fix

#260 [#172] 리뷰 삭제 Alert 추가
  EATSSU/App/Sources/Presentation/MyPage/ViewController/MyReviewViewController.swift
Labels: 🛠️ Fix

#265 [#264] latestVersion > currentVersion인 경우에만 강제 업데이트 알럿 설정
  EATSSU/App/Sources/Utility/Application/SceneDelegate.swift
Labels: 🚨 HotFix

#267 [#266] Splash 뷰 기본 버전으로 변경
  EATSSU/App/Sources/Utility/Application/SceneDelegate.swift
Labels: 🛠️ Fix
